### ISSUE TITLE
Discrepancy in Reward Metrics

### ISSUE THREAD

**Issue by guestreturn** [rbokade/pytsc#2]
Hello, I'm very interested in your PyTSC project. However, while reproducing the results from the paper, I encountered a few issues. Firstly, the y-axis of the learning curves in the paper represents the reward, which ranges below -100, for example, in the jinan_3_4 scenario, the reward is between -1000 and -200. However, in the EPymarl framework, the implemented test_return_mean is around -8. I have chosen **QueueLength** as the reward metric, and the observation_space is **lane_features**. I'm curious why there is this inconsistency.

**Comment by rbokade** [comment]
The reward function in the code was later scaled by number of intersections (global reward / # intersections). This is where the discrepancy arises. 
```
def get_global_reward(self):
        fc = self.config.misc["flickering_coef"]
        reward = 1e-6
        reward += fc * self.metrics.flickering_signal
        reward += self.metrics.n_queued_norm
        return -1 * reward
```
I would recommend using the scaled version of the reward (since it was seed to perform better) and track queue length separately.

**Comment by rbokade** [comment]
The reward function in the code was later scaled by number of intersections (global reward / # intersections). This is where the discrepancy arises. 
```
def get_global_reward(self):
        fc = self.config.misc["flickering_coef"]
        reward = 1e-6
        reward += fc * self.metrics.flickering_signal
        reward += self.metrics.n_queued_norm
        return -1 * reward
```
I would recommend using the scaled version of the reward (since it was seed to perform better) and track queue length separately.
